# Generated by Django 5.1.7 on 2025-03-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="earned_points",
            field=models.IntegerField(default=0),
        ),
    ]
